In [1]:
import numpy as np
import math 

### <sapn style="color:#f0f0f0">Working on Matric Calculation</span>

In [2]:
x=np.array([0,1,2])

In [3]:
x*x

array([0, 1, 4])

In [4]:
np.inner(x,x)

5

In [5]:
np.outer(x,x)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [6]:
np.dot(x,x)

5

In [7]:
x.T

array([0, 1, 2])

In [8]:
x_1=x[:,None]

In [9]:
np.dot(x,x_1)

array([5])

In [10]:
x_1*x 

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [11]:
x*x_1 #ohh?

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [12]:
#np.dot(x_1,x) #error
np.dot(x[x_1],x[None,:])

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

<sapn style="color:#f0f0f0">Einstein summation convention</span>

In [13]:
X=np.array([[i,j+i] for i in range(2) for j in range(2)])
np.einsum('ij,kj->ik',X,X)

array([[0, 0, 0, 0],
       [0, 1, 1, 2],
       [0, 1, 2, 3],
       [0, 2, 3, 5]])

In [14]:
np.einsum('ij,jk->ik',X,X.T)

array([[0, 0, 0, 0],
       [0, 1, 1, 2],
       [0, 1, 2, 3],
       [0, 2, 3, 5]])

In [15]:
np.einsum('ij,jk->ik',X.T,X)

array([[2, 3],
       [3, 6]])

In [16]:
np.einsum('i,j->ij',x,x)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [17]:
np.einsum('i,i->',x,x)

5

In [18]:
X.T

array([[0, 0, 1, 1],
       [0, 1, 1, 2]])

In [19]:
np.dot(X,X.T)

array([[0, 0, 0, 0],
       [0, 1, 1, 2],
       [0, 1, 2, 3],
       [0, 2, 3, 5]])

In [20]:
x.ravel()[:, np.newaxis]*x.ravel()[np.newaxis,:]

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [21]:
np.matmul(x,x)

5

In [22]:
np.matmul(x.T,x) ##np.matmul(x,x.T)

5

In [23]:
np.matmul(X.T,X)

array([[2, 3],
       [3, 6]])

In [24]:
np.matmul(X,X.T)

array([[0, 0, 0, 0],
       [0, 1, 1, 2],
       [0, 1, 2, 3],
       [0, 2, 3, 5]])

In [25]:
np.dot(1,X) #np.matmul(1,X) #error

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 2]])

In [26]:
a=np.arange(2*2*4).reshape((2,2,4))
b=np.arange(2*2*4).reshape((2,4,2))
ab=np.matmul(a,b);ab[0,1,1]

98

In [27]:
c=np.arange(2*3*4*2).reshape((2,3,4,2))
d=np.arange(2*3*4*2).reshape((2,3,2,4))
cd=np.matmul(c,d);cd[0,2,2,2]

822

In [28]:
#cd #you can't check

### <sapn style="color:#f0f0f0">Advancint Numpy</span>

In [29]:
e=np.array([[1, 2], 
            [3, 4]]) 
f=np.array([[5, 6], 
            [7, 8]]) 

In [30]:
np.vstack((e,f)) #be carefull its double open brakets(())

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
np.hstack((e,f))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
np.concatenate((e, f),0) # 0 is default 1 is equal to colums_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
g=np.array([0,0])
np.column_stack((e, f, g)) # different dimension also are acceptable

array([[1, 2, 5, 6, 0],
       [3, 4, 7, 8, 0]])

In [34]:
h=np.array([[1, 3, 5, 7, 9, 11], 
            [2, 4, 6, 8, 10, 12]]) 

In [35]:
np.hsplit(h,2)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [36]:
np.vsplit(h,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [37]:
np.array_split(h,3,axis=0)

[array([[ 1,  3,  5,  7,  9, 11]]),
 array([[ 2,  4,  6,  8, 10, 12]]),
 array([], shape=(0, 6), dtype=int64)]

In [38]:
for a in np.array_split(h,3,axis=1):
    print(a)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
[[ 9 11]
 [10 12]]


<span style="font-weight:bold">The Broadcasting Rule: In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.</span>

In [39]:
i=np.array([1.0, 2.0, 3.0]) 
j=2.0
k=[2.0, 2.0] 

In [40]:
i*j # i*k is error 3x2

array([ 2.,  4.,  6.])

In [41]:
l=np.array([[0,1,2],[3,4,5]]);l*i

array([[  0.,   2.,   6.],
       [  3.,   8.,  15.]])

In [42]:
m=np.array([np.dot([np.dot([i_ for i_ in range(1,4) ],j_) for j_ in range(1,4)],k_) for k_ in range(1,4)]);m

array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9]],

       [[ 2,  4,  6],
        [ 4,  8, 12],
        [ 6, 12, 18]],

       [[ 3,  6,  9],
        [ 6, 12, 18],
        [ 9, 18, 27]]])

In [43]:
i*m

array([[[  1.,   4.,   9.],
        [  2.,   8.,  18.],
        [  3.,  12.,  27.]],

       [[  2.,   8.,  18.],
        [  4.,  16.,  36.],
        [  6.,  24.,  54.]],

       [[  3.,  12.,  27.],
        [  6.,  24.,  54.],
        [  9.,  36.,  81.]]])

In [44]:
i[...,None]*k #i is 3*1, k is 1x2

array([[ 2.,  2.],
       [ 4.,  4.],
       [ 6.,  6.]])

### <sapn style="color:#f0f0f0">Working with datetime64</span>

In [45]:
today=np.datetime64('2018-11-21');today

numpy.datetime64('2018-11-21')

In [46]:
np.datetime64(today,'Y'),np.datetime64(today,'W')

(numpy.datetime64('2018'), numpy.datetime64('2018-11-15'))

In [47]:
date_range=np.arange('2018-11','2018-12',dtype='datetime64[D]')

In [48]:
today in date_range

True

In [49]:
dur=np.datetime64('2018-11-20')-np.datetime64('2017-11-20');dur

numpy.timedelta64(365,'D')

In [50]:
np.timedelta64(dur,'W') ##52 weeks during a year

numpy.timedelta64(52,'W')

In [51]:
random_dates=np.array(['2019-03-10','2018-10-10','2019-10-10'],dtype='datetime64');np.sort(random_dates)

array(['2018-10-10', '2019-03-10', '2019-10-10'], dtype='datetime64[D]')

In [52]:
# coefficients 
a=np.array([[1, 2], [3, 4]]) 
# constants 
b=np.array([8, 18]) 
np.linalg.solve(a, b)

array([ 2.,  3.])

### <sapn style="color:#f0f0f0">So useful Coutner Methods</span>

In [53]:
from collections import Counter

In [54]:
t=[(111,1,'member1_name'),(222,2,'member2'),(333,3,'member3_name'),(222,2,'member2')];len(t)

4

In [55]:
Counter(e for e in t)

Counter({(111, 1, 'member1_name'): 1,
         (222, 2, 'member2'): 2,
         (333, 3, 'member3_name'): 1})

In [56]:
#or you can even specify which data to count
m=Counter(e[0] for e in t)

In [57]:
sum(v for k, v in m.items() if k is 222)

2

In [58]:
for k, v in m.items(): print(k,v)

333 1
222 2
111 1


#### <sapn style="color:#f0f0f0">most_common returns more frequent values. Set 1 means most frequent values. Set none means returning all values with sorting. </span>

In [59]:
m.most_common(1)

[(222, 2)]

In [60]:
(id_, count),=m.most_common(1);[(id_,count)] #unpacking

[(222, 2)]

### <sapn style="color:#f0f0f0">Random Numbers</span>

<sapn style="color:#f0f0f0">sigma * np.random.randn(...) + mu, is the same as </span> 
<sapn style="color:#f0f0f0">np.random.normal(loc= mu, scale= sigma, ...)</span><br/>
<a href='https://stackoverflow.com/questions/21738383/python-difference-between-randn-and-normal'>difference of above two random variable generation function</a>

In [61]:
## Both are the exact same thing
np.random.seed(1111)
np.random.normal(size= (3, 3))

array([[-1.30001032, -1.07298904,  0.79019919],
       [-0.8782655 ,  1.50182182, -0.02392945],
       [ 0.27594888, -0.96639308, -1.58031468]])

In [62]:
np.random.seed(1111)
np.random.randn(3, 3)

array([[-1.30001032, -1.07298904,  0.79019919],
       [-0.8782655 ,  1.50182182, -0.02392945],
       [ 0.27594888, -0.96639308, -1.58031468]])

<span style="color:#0f0f0f;font-weight:bold;">inplace, bitwise OR operation, and performs union operation of Python sets.</span><br/>
<a href='https://stackoverflow.com/questions/3929278/what-does-ior-do-in-python'>what is |= for?</a>

In [63]:
v_1,v_2,v_3,v_4=True,True,False,False
v_1|v_2

True

In [64]:
v_3

False

In [65]:
v_3|=v_1;v_3

True

### <p style="color:#0f0f0f">Pandas DataFame Brushing up</p>
<a href="https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.join.html">Pandas Join</a>

In [66]:
import pandas as pd
x,y=[0,0],[0,0]
df=pd.DataFrame(list(zip(*(x,y))),dtype='int',columns=['aaa','bbb']);df

aaa  bbb
0    0    0
1    0    0

In [67]:
df.append({'aaa': 2,'bbb':2}, ignore_index=True)

aaa  bbb
0    0    0
1    0    0
2    2    2

In [68]:
ziped=list(zip(*([1,1],[1,1])))
pd.concat([df,pd.DataFrame(ziped,columns=df.columns)], ignore_index=True)

aaa  bbb
0    0    0
1    0    0
2    1    1
3    1    1

In [69]:
l=len(df.loc[:,'aaa'])
new=np.arange(l)
ddf=pd.DataFrame(new,columns=['CCC'])

In [70]:
df.join(ddf)
#df.join(ddf, lsuffix='_caller', rsuffix='_other')

aaa  bbb  CCC
0    0    0    0
1    0    0    1

In [71]:
pd.concat([df, ddf], axis=1)

aaa  bbb  CCC
0    0    0    0
1    0    0    1

In [72]:
df=pd.DataFrame(list(zip(*(x,y))),dtype='int',columns=['aaa','bbb']);df
new_col=ddf.values  # can be a list, a Series, an array or a scalar   
df.insert(loc=0,column='CCC',value=new_col);df

CCC  aaa  bbb
0    0    0    0
1    1    0    0

In [73]:
cols=df.columns.tolist()
#cols = [cols[-1]]+cols[:-1] # or whatever change you need
cols=cols[1:]+[cols[0]]
df.reindex(columns=cols)

aaa  bbb  CCC
0    0    0    0
1    0    0    1

In [74]:
df.reindex(columns=['bbb']+df.columns[:-1].tolist())

bbb  CCC  aaa
0    0    0    0
1    0    1    0

In [75]:
df[[cols[i] for i in reversed(range(len(cols)))]]

CCC  bbb  aaa
0    0    0    0
1    1    0    0

In [76]:
df[[cols[i] for i in range(len(cols)-1,-1,-1)]]

CCC  bbb  aaa
0    0    0    0
1    1    0    0

In [77]:
z=np.column_stack((df.values,[9,9]));z

array([[0, 0, 0, 9],
       [1, 0, 0, 9]])

In [78]:
pd.DataFrame(z,columns=df.columns.tolist()+['new'])

CCC  aaa  bbb  new
0    0    0    0    9
1    1    0    0    9

### <p style="color:#0f0f0f">Python Critical Tools</p>

In [79]:
d=dict(a=1,b=2)
for i,v in enumerate(d): print(i,v)

0 b
1 a


In [80]:
for i,(k,v) in enumerate(zip(list(d.keys()),list(d.values()))):
    print(i,(k,v))

0 ('b', 2)
1 ('a', 1)


In [81]:
def reformat_date(mdy_date_string):
    year,month,day = mdy_date_string.split('/')
    return "{}-{}-{}".format(year,month,day)

In [82]:
reformat_date('2001/02/11')

'2001-02-11'

In [83]:
numbers=[1, 2, 3, 4, 5, 6]
*rest, last=numbers;last ## alternative for numbers[-1]

6

In [84]:
s_points = [(1,2), (3,4), (5,6)]
e_points = [(-1,-2), (-3,4), (-6,-5)]
for (s1,s2),(e1,e2) in zip(s_points,e_points):
    print(s1,s2,e1,e2)

1 2 -1 -2
3 4 -3 4
5 6 -6 -5


<p style='color:0f0f0f'>__iter__ dunder method</p>

In [85]:
class RepeaterIterator:
    def __init__(self, source):
        print('inside RepeaterIterator:__init__:',source)
        self.source = source
    def __next__(self):
        print('inside RepeaterIterator:__next__:',self.source.value)
        return self.source.value
    
class Repeater:
    def __init__(self, value):
        print('inside Repeater:__init__:',value)
        self.value = value
    def __iter__(self):
        print('inside Repeater:__iter__:',self)
        return RepeaterIterator(self)

In [86]:
n=0
repeater=Repeater('Hello')
for item in repeater:
    print(item)
    if n==5: break
    n=n+1

inside Repeater:__init__: Hello
inside Repeater:__iter__: <__main__.Repeater object at 0x1199d19e8>
inside RepeaterIterator:__init__: <__main__.Repeater object at 0x1199d19e8>
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello


In [87]:
nn=0
iterator=repeater.__iter__()
while nn<6:
    item = iterator.__next__()
    print(item)
    nn+=1

inside Repeater:__iter__: <__main__.Repeater object at 0x1199d19e8>
inside RepeaterIterator:__init__: <__main__.Repeater object at 0x1199d19e8>
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello
inside RepeaterIterator:__next__: Hello
Hello


In [88]:
iterator=iter(repeater); print('\n')
next(iterator);next(iterator)

inside Repeater:__iter__: <__main__.Repeater object at 0x1199d19e8>
inside RepeaterIterator:__init__: <__main__.Repeater object at 0x1199d19e8>


inside RepeaterIterator:__next__: Hello
inside RepeaterIterator:__next__: Hello


'Hello'

In [89]:
l=[1,2,3]
it=iter(l);next(it)

1

In [90]:
class BoundedRepeater:
    def __init__(self, value, max_repeats):
        self.value = value
        self.max_repeats = max_repeats
        self.count = 0

    def __iter__(self): return self

    def __next__(self):
        if self.count >= self.max_repeats:
            raise StopIteration
        self.count+= 1
        return self.value

In [91]:
repeater_2=BoundedRepeater('hello',3)
it=iter(repeater_2)
for i,v in enumerate(it): print(i,v)

0 hello
1 hello
2 hello


In [92]:
re_defined=BoundedRepeater('hello',3); it=iter(re_defined)
while True:
    try:
        item = next(it)
    except StopIteration:
        break
    print(item)

hello
hello
hello


In [93]:
s=[1,2,3,4,1]
s[1:-1:1] # index 1 to last, step 1

[2, 3, 4]

In [94]:
s.count(1) # value counter

2

In [95]:
s.index(1) # get index of first match?

0

In [96]:
a=[-2,1,5,3,8,5,6]
b=[1,2,5] # aleady know which indice to extrace values
c=[ a[i] for i in b];c

[1, 5, 5]

In [97]:
from operator import itemgetter 
print (itemgetter(*b)(a))

(1, 5, 5)


In [98]:
aa=np.array(a);list(aa[b])

[1, 5, 5]

In [99]:
list(map(a.__getitem__, b))

[1, 5, 5]

In [100]:
aaa=pd.Series([-2, 1, 5, 3, 8, 5, 6]);r_=aaa[b]
list(r_)

[1, 5, 5]

In [101]:
for i,v in zip(r_.index,r_.values):
    print(i,v)

1 1
2 5
5 5


In [102]:
a=[-2,1,5,3,8,5,6]
ix=np.in1d(x, b) #very useful when comparion to list #isin no logner works
np.where(ix) #return just indice where is True

(array([], dtype=int64),)

In [103]:
np.array(a)[np.where(ix)[0].tolist()]

array([], dtype=int64)

In [104]:
l_2=np.arange(12).reshape((3,4));l_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
condition_1=np.mod(l_2,3)==0 #remain equals to 0

In [106]:
c_2=np.mod(l_2,3)==1

In [107]:
all_=np.append(np.extract(condition_1,l_2) ,np.extract(c_2,l_2));np.sort(all_)

array([ 0,  1,  3,  4,  6,  7,  9, 10])

In [108]:
whereisNonzero=np.array([[1,0,2], [3,4,0], [5,6,0]],dtype='f');whereisNonzero

array([[ 1.,  0.,  2.],
       [ 3.,  4.,  0.],
       [ 5.,  6.,  0.]], dtype=float32)

In [109]:
nzero=np.nonzero(whereisNonzero)
#whereisNonzero[nzero]=10;whereisNonzero
'''
array([[10,  0, 10],
       [10, 10,  0],
       [10, 10,  0]])
'''

'\narray([[10,  0, 10],\n       [10, 10,  0],\n       [10, 10,  0]])\n'

In [110]:
m=whereisNonzero.mean(axis=0) # mean by column
#for index,column in zip(nzero[0],nzero[1]):
for index,column in zip(*nzero): #otherwise 2d array
    whereisNonzero[index,column]=m[column] #whereisNonzero[index,column]===whereisNonzero[index][column]
whereisNonzero

array([[ 3.        ,  0.        ,  0.66666669],
       [ 3.        ,  3.33333325,  0.        ],
       [ 3.        ,  3.33333325,  0.        ]], dtype=float32)

In [111]:
nay=np.array([[1,1], [0,0]])
nay.sort(axis=0);nay

array([[0, 0],
       [1, 1]])

In [112]:
def countdown(num):
    print('Starting')
    while num > 0:
        yield num
        num -= 1

In [113]:
o=countdown(5);next(o)

Starting


5

In [114]:
my_list=['a','b','c','d']
gen_obj=(x for x in my_list);gen_obj

<generator object <genexpr> at 0x1199bafc0>

In [115]:
next(gen_obj)

'a'

In [116]:
for val in gen_obj:
    print(val)

b
c
d


In [117]:
import cProfile
cProfile.run('sum((i * 2 for i in range(10000000) if i % 3 == 0 or i % 5 == 0))')

         4666672 function calls in 6.151 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  4666668    5.577    0.000    5.577    0.000 <string>:1(<genexpr>)
        1    0.000    0.000    6.151    6.151 <string>:1(<module>)
        1    0.000    0.000    6.151    6.151 {built-in method builtins.exec}
        1    0.574    0.574    6.151    6.151 {built-in method builtins.sum}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [118]:
cProfile.run('sum([i * 2 for i in range(10000000) if i % 3 == 0 or i % 5 == 0])')

         5 function calls in 5.728 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    5.557    5.557    5.557    5.557 <string>:1(<listcomp>)
        1    0.096    0.096    5.728    5.728 <string>:1(<module>)
        1    0.000    0.000    5.728    5.728 {built-in method builtins.exec}
        1    0.074    0.074    0.074    0.074 {built-in method builtins.sum}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [119]:
import requests
import re
def get_pages(link):
    links_to_visit = []
    links_to_visit.append(link)
    while links_to_visit:
        current_link = links_to_visit.pop(0)
        page = requests.get(current_link)
        for url in re.findall('<a href="([^"]+)">', str(page.content)):
            if url[0] == '/':
                url = current_link + url[1:]
            pattern = re.compile('https?')
            if pattern.match(url):
                links_to_visit.append(url)
        yield current_link


webpage = get_pages('http://sample.com')
#for result in webpage: print(result)

### <a href="https://realpython.com/python-itertools/" style="color:#0f0f0f">Itertools Recap</a>

In [120]:
list(map(len, ['abc', 'de', 'fghi']))

[3, 2, 4]

In [121]:
list(map(sum, zip([1, 2, 3], [4, 5, 6])))

[5, 7, 9]

In [122]:
def naive_grouper(inputs, n):
    num_groups = len(inputs) // n
    return [tuple(inputs[i*n:(i+1)*n]) for i in range(num_groups)]

In [123]:
def better_grouper(inputs, n):
    iters = [iter(inputs)] * n
    return zip(*iters) # zipping refer 0 to 1, seeming comparing 0 to 0. The two list is the same id.

In [10]:
nums=np.arange(10)
iters=[iter(nums)] * 2
list(id(itr) for itr in iters)

[47793491808, 47793491808]

In [125]:
list(better_grouper(nums,2))

[(0, 1), (2, 3), (4, 5), (6, 7), (8, 9)]

In [11]:
import toolz
list(toolz.partition_all(2, nums)) #toolz library

[(0, 1), (2, 3), (4, 5), (6, 7), (8, 9)]

In [127]:
list(zip(*[iter([0,1,2])]*2))

[(0, 1)]

In [2]:
import itertools as it
x,y=[1,2,3,4,5], ['a','b','c']
list(zip(x, y))

[(1, 'a'), (2, 'b'), (3, 'c')]

In [129]:
list(it.zip_longest(x, y))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, None), (5, None)]

In [130]:
def grouper(inputs, n, fillvalue=None):
    iters = [iter(inputs)] * n
    return it.zip_longest(*iters, fillvalue=fillvalue)

In [131]:
list(grouper(nums,4))

[(0, 1, 2, 3), (4, 5, 6, 7), (8, 9, None, None)]

In [132]:
bills=[20,20,20,10,10,10,10,10,5,5,5,5,1,1,1,1,1]
makes_37=[]
sum_of_combination=37;
sof=sum_of_combination
for n in range(1, len(bills) + 1):
    for c in it.combinations(bills, n):
        if sum(c)==sof:
            makes_37.append(c)
set(makes_37)

{(10, 10, 5, 5, 5, 1, 1),
 (10, 10, 10, 5, 1, 1),
 (20, 5, 5, 5, 1, 1),
 (20, 10, 5, 1, 1)}

In [4]:
list(it.combinations_with_replacement([20,1], 2))

[([20, 1], [20, 1]), ([20, 1], [4, 5]), ([4, 5], [4, 5])]

In [7]:
list(it.combinations([[0,1],[2,3]], 2))# combination from two set hopefully but not.

[([0, 1], [2, 3])]

In [134]:
makes_37=[]
for n in range(1, len(bills) + 1):
    for c in it.combinations_with_replacement([20,10,5,1],n):
        if sum(c)==sof:
            makes_37.append(c)
set(makes_37)

{(5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
 (5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1),
 (5, 5, 5, 5, 5, 5, 5, 1, 1),
 (10, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
 (10, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1),
 (10, 5, 5, 5, 5, 5, 1, 1),
 (10, 10, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
 (10, 10, 5, 5, 1, 1, 1, 1, 1, 1, 1),
 (10, 10, 5, 5, 5, 1, 1),
 (10, 10, 10, 1, 1, 1, 1, 1, 1, 1),
 (10, 10, 10, 5, 1, 1),
 (20, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
 (20, 5, 5, 1, 1, 1, 1, 1, 1, 1),
 (20, 5, 5, 5, 1, 1),
 (20, 10, 1, 1, 1, 1, 1, 1, 1),
 (20, 10, 5, 1, 1)}

In [135]:
list(it.permutations(['a', 'b', 'c']))

[('a', 'b', 'c'),
 ('a', 'c', 'b'),
 ('b', 'a', 'c'),
 ('b', 'c', 'a'),
 ('c', 'a', 'b'),
 ('c', 'b', 'a')]

In [136]:
def evens():
    n=0
    while True:
        yield n
        n+=2
E=evens()
list(next(E) for _ in range(5))

[0, 2, 4, 6, 8]

In [137]:
counter_=it.count()
list(next(counter_) for _ in range(5))

[0, 1, 2, 3, 4]

In [138]:
E_2=it.count(step=2)
list(next(E_2) for _ in range(5))

[0, 2, 4, 6, 8]

In [139]:
O_=it.count(start=1,step=2)
list(next(O_) for _ in range(5))

[1, 3, 5, 7, 9]

In [140]:
list(zip(it.count(), ['a', 'b', 'c']))

[(0, 'a'), (1, 'b'), (2, 'c')]

In [141]:
def fibs():
    a,b=0,1
    while True:
        yield a
        a,b=b,a+b

In [142]:
F=fibs()
list(next(F) for _ in range(10))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [143]:
list(it.repeat(1, 5))

[1, 1, 1, 1, 1]

In [144]:
def accumulate(inputs, func):
    itr = iter(inputs)
    prev = next(itr)
    for cur in itr:
        yield prev
        prev = func(prev, cur)

In [145]:
list(accumulate([1,2,3,4,5],np.add))

[1, 3, 6, 10]

In [146]:
list(it.accumulate([1,2,3,4,5]))

[1, 3, 6, 10, 15]

In [147]:
list(it.accumulate([9, 21, 17, 5, 11, 12, 2, 6], min))

[9, 9, 9, 5, 5, 5, 2, 2]

In [148]:
list(it.accumulate([9, 21, 17, 5, 11, 12, 2, 6], lambda x,y:np.array([x,y]).min()))

[9, 9, 9, 5, 5, 5, 2, 2]

In [378]:
def first_order(p,q,initial_val):
    """Return sequence defined by s(n) = p * s(n-1) + q."""
    #print(type(it.repeat(initial_val)))
    return it.accumulate(it.repeat(initial_val), lambda s,_:p*s+q)

In [379]:
evens=first_order(p=1, q=2, initial_val=0)
list(next(evens) for _ in range(5))

[0, 2, 4, 6, 8]

In [150]:
def second_order(p, q, r, initial_values):
    """Return sequence defined by s(n) = p * s(n-1) + q * s(n-2) + r."""
    intermediate = it.accumulate(
        it.repeat(initial_values),
        lambda s,_: (s[1], p*s[1] + q*s[0] + r)
    )
    return map(lambda x: x[0], intermediate)

In [277]:
fibs=second_order(p=1, q=1, r=0, initial_values=(0, 1))
list(next(fibs) for _ in range(8))

[0, 1, 1, 2, 3, 5, 8, 13]

In [261]:
it_1, it_2=it.tee([1,2,3,4,5],2)
for _ in it_1: pass;
print(list(it_1))

[]


In [262]:
list(it_2) #iterate individually

[1, 2, 3, 4, 5]

In [263]:
list(it.islice('ABCDEFG', 2, 5))

['C', 'D', 'E']

In [264]:
list(it.islice([1, 2, 3, 4, 5], 0, 5, 2))

[1, 3, 5]

In [265]:
list(it.islice(range(10), 3, None))

[3, 4, 5, 6, 7, 8, 9]

In [269]:
list(it.islice('ABCDE', 4))

['A', 'B', 'C', 'D']

In [271]:
list(it.chain([1, 2], [3, 4, 5, 6], [7, 8, 9]))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [353]:
list(it.chain.from_iterable([[1, 2, 3], [4, 5, 6]]))

[1, 2, 3, 4, 5, 6]

In [383]:
list(it.chain.from_iterable(['abcde','12345']))

['a', 'b', 'c', 'd', 'e', '1', '2', '3', '4', '5']

In [354]:
cycle = it.chain.from_iterable(it.repeat('abc'))
list(it.islice(cycle, 8))

['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b']

In [385]:
list(it.compress('ABCDEF', [1,0,1,0,1,1]))

['A', 'C', 'E', 'F']

In [387]:
list(it.filterfalse(lambda x: x%2, range(10))) ##since 0 is false

[0, 2, 4, 6, 8]

In [392]:
list(it.starmap(pow, [[2,5], {3,2}, (10,3)]))

[32, 8, 1000]

In [396]:
list(it.combinations_with_replacement([1,3],2))

[(1, 1), (1, 3), (3, 3)]

In [397]:
list(it.combinations_with_replacement('13',2))

[('1', '1'), ('1', '3'), ('3', '3')]

In [158]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [159]:
(1,2)+(3,4)

(1, 2, 3, 4)

#### <a href="https://stackoverflow.com/questions/38987/how-to-merge-two-dictionaries-in-a-single-expression">Merging dict awesome info</a>

#### <span>Amazing Dict merging tech</span>

In [183]:
x,y,z,w=dict(a=1,b=2),dict(a=3,c=4),dict(c=3,d=4),dict()

In [184]:
w.update(x);w

{'a': 1, 'b': 2}

In [185]:
w.update(y);w

{'a': 3, 'b': 2, 'c': 4}

In [186]:
[(lambda w=w: w.update(d))() for d in [x,y,z]];w

{'a': 3, 'b': 2, 'c': 3, 'd': 4}

In [187]:
w=(lambda f=x.copy(): (f.update(y), f)[1])();w

{'a': 3, 'b': 2, 'c': 4}

In [188]:
w=(lambda f=x.copy(): f.update(y) or f)();w #`or f` is necessary bc when update is success, it returns None.

{'a': 3, 'b': 2, 'c': 4}

In [190]:
#not what I meant
#have to be func tool, like lambda
#(lambda f: compose(f.update(y), do(w.append)))(x.copy());w

In [191]:
log_=[]
inc = lambda x: x
inc = compose(inc, do(log_.append))
inc(x)

{'a': 1, 'b': 2}

In [192]:
log_

[{'a': 1, 'b': 2}]

In [193]:
(x.update(y), x)

(None, {'a': 3, 'b': 2, 'c': 4})

In [194]:
merge=lambda *args: dict(it.chain.from_iterable(list(map(dict.items, args))))

In [195]:
merge(x,y)

{'a': 3, 'b': 2, 'c': 4}

In [196]:
merge(x,y,z)

{'a': 3, 'b': 2, 'c': 3, 'd': 4}

In [197]:
from functools import reduce
def merge_dicts(*dicts):
    return reduce(lambda a, d: a.update(d) or a, dicts, {}) # the last {} is unnecessary

In [198]:
merge_dicts(x,y,z)

{'a': 3, 'b': 2, 'c': 3, 'd': 4}

In [199]:
n,l=2,3
(lambda n=n:n*l)()

6

#### <p>* iterable unpacking operator and ** dictionary unpacking operators to allow unpacking in more positions</p>

In [200]:
x,y,w=dict(a=1,b=2),dict(a=3,c=4),[]
z={**x, **y};z

{'a': 3, 'b': 2, 'c': 4}

In [202]:
a=[1,2]
[*a, *[2], 3]

[1, 2, 2, 3]

In [203]:
*range(4), 4

(0, 1, 2, 3, 4)

In [204]:
[*range(4), 4]

[0, 1, 2, 3, 4]

In [205]:
{*range(4), 4} #making set

{0, 1, 2, 3, 4}

In [206]:
ranges=[range(i) for i in range(5)];ranges

[range(0, 0), range(0, 1), range(0, 2), range(0, 3), range(0, 4)]

In [207]:
dict(x.items()|y.items())

{'a': 1, 'b': 2, 'c': 4}

In [208]:
dict(x, **y)

{'a': 3, 'b': 2, 'c': 4}

In [209]:
dict(it.chain(x.items(), y.items()))

{'a': 3, 'b': 2, 'c': 4}

In [210]:
from collections import ChainMap
dict(ChainMap({}, y, x))

{'a': 3, 'b': 2, 'c': 4}

In [211]:
{i:d[i] for d in [x,y] for i in d}

{'a': 3, 'b': 2, 'c': 4}

In [212]:
def dictmerge(*args): 
    return {i:d[i] for d in args for i in d}
dictmerge(x,y)

{'a': 3, 'b': 2, 'c': 4}

In [213]:
dict(Counter(x) | Counter(y)) #whatever dict form.... Counter({'a': 1, 'b': 2})... then, 

{'a': 3, 'b': 2, 'c': 4}

#### <p>Amazing Python library Toolz <a href='https://toolz.readthedocs.io/en/latest/api.html#toolz.dicttoolz.merge'>Docs</a></p>

In [14]:
from toolz import *
import toolz.dicttoolz as dtoolz

In [215]:
dtoolz.merge(x,y,z)

{'a': 3, 'b': 2, 'c': 4}

In [216]:
dtoolz.merge_with(sum,x,y,z)

{'a': 7, 'b': 4, 'c': 8}

In [217]:
dtoolz.keymap(str.upper,x)

{'A': 1, 'B': 2}

In [218]:
dtoolz.itemmap(reversed, x)

{1: 'a', 2: 'b'}

In [219]:
iseven=lambda x: x % 2 == 0
d_={1: 2, 2: 3, 3: 4, 4: 5}
dtoolz.valfilter(iseven,d_)

{1: 2, 3: 4}

In [220]:
dtoolz.keyfilter(iseven,d_)

{2: 3, 4: 5}

In [221]:
X_=[0,1,2]
[toolz.pipe(x_, lambda x:x*x, lambda y:y==4) for x_ in X_] #pipe accept only single arg, no list

[False, False, True]

In [222]:
list(diff([1, 2, 3], [1, 2, 10, 100]))

[(3, 10)]

In [223]:
data=[{'id': 1, 'name': 'Cheese'}, {'id': 2, 'name': 'Pies'}]
list(pluck('name', data))

['Cheese', 'Pies']

In [224]:
list(partition_all(2, [1, 2, 3, 4]))

[(1, 2), (3, 4)]

In [225]:
list(sliding_window(2, [1,2,3,4]))

[(1, 2), (2, 3), (3, 4)]

In [226]:
list(map(np.mean,(sliding_window(2, [1,2,3,4]))))

[1.5, 2.5, 3.5]

In [227]:
double=lambda x: x*2
powers_of_two=iterate(double,1)
for _ in range(3):
    print(next(powers_of_two))

1
2
4


In [228]:
frequencies(['cat', 'cat', 'ox', 'pig', 'pig', 'cat'])

{'cat': 3, 'ox': 1, 'pig': 2}

In [229]:
list(interpose("a", [1, 2, 3]))

[1, 'a', 2, 'a', 3]

In [230]:
list(mapcat(lambda s: [c.upper() for c in s],[["a", "b"], ["c", "d", "e"]]))

['A', 'B', 'C', 'D', 'E']

In [162]:
from toolz import *
list(concat([[], [1], (2, 3)]))

[1, 2, 3]

In [163]:
list(concatv([], ["a"], ["b", "c"]))

['a', 'b', 'c']

In [164]:
''.join(interleave(('ABC', 'XY')))

'AXBYC'

In [165]:
list(merge_sorted([1, 3, 5], [2, 4, 6]))

[1, 2, 3, 4, 5, 6]

In [166]:
names = ['Alice', 'Bob', 'Charlie', 'Dan', 'Edith', 'Frank']
groupby(len, names) 

{3: ['Bob', 'Dan'], 5: ['Alice', 'Edith', 'Frank'], 7: ['Charlie']}

In [167]:
groupby('gender', [{'name': 'Alice', 'gender': 'F'},{'name': 'Bob', 'gender': 'M'},{'name': 'Charlie', 'gender': 'M'}])

{'F': [{'gender': 'F', 'name': 'Alice'}],
 'M': [{'gender': 'M', 'name': 'Bob'}, {'gender': 'M', 'name': 'Charlie'}]}

In [168]:
from functools import partial, reduce
sum_=partial(reduce, np.add)

In [169]:
sum_([1,2,3,4])

10

In [172]:
iseven=lambda x: x % 2 == 0
list(remove(iseven, [1, 2, 3, 4]))

[1, 3]

In [173]:
inc = lambda x: x + 1
double = lambda x: x * 2
juxt(inc, double)(10)

(11, 20)

#### <p>compose(f, g, h)(x, y) is the same as f(g(h(x, y))</p><p>Opposite flow frorm pipe func h(g(f(x))</p>

In [21]:
f_1 = lambda i: i + 1
f_2 = lambda i: str(i) + 'HI!'
compose(f_2, f_1)(3)

'4HI!'

In [22]:
from toolz.curried import do
log = []
f = lambda x: x + 2
inc = compose(f, do(log.append))
inc(2)

4

In [176]:
log

[2]

In [17]:
from toolz import curry
@curry
def mul(x,y): return x*y
double = mul(2) #witing for second arg

In [18]:
double(3)

6

In [233]:
def stem(word): 
    """ Stem word to primitive form """
    return word.lower().rstrip(",.!:;'-\"").lstrip("'\"")
map=curry(map)
# wordcount = compose(frequencies, partial(map, stem), str.split)
wordcount=compose(frequencies, map(stem), str.split)

In [234]:
wordcount('Hello world! I\'m from the space! Hello human')

{'from': 1, 'hello': 2, 'human': 1, "i'm": 1, 'space': 1, 'the': 1, 'world': 1}

In [235]:
assoc({'x': 1}, 'x', 2)

{'x': 2}

In [236]:
assoc({'x': 1}, 'y', 3) 

{'x': 1, 'y': 3}

In [237]:
dissoc({'x': 1, 'y': 2}, 'y')

{'x': 1}

In [238]:
dissoc({'x': 1, 'y': 2}, 'y', 'x')

{}

##### <p>Assoc for hested dictionary</p>

In [239]:
purchase = {'name': 'Alice', 
            'order': {'items': ['Apple', 'Orange'], 
                      'costs': [0.50, 1.25]}, 
            'credit card': '5555-1234-1234-1234'}
assoc_in(purchase, ['order', 'costs'], [0.25, 1.00])

{'credit card': '5555-1234-1234-1234',
 'name': 'Alice',
 'order': {'costs': [0.25, 1.0], 'items': ['Apple', 'Orange']}}

In [240]:
update_in(purchase, ['order', 'costs'], sum)

{'credit card': '5555-1234-1234-1234',
 'name': 'Alice',
 'order': {'costs': 1.75, 'items': ['Apple', 'Orange']}}

In [241]:
update_in({}, [1, 2, 3], str, default="bar")

{1: {2: {3: 'bar'}}}

In [242]:
update_in({1: 'foo'}, [2, 3, 4], lambda x:x+1, 0)

{1: 'foo', 2: {3: {4: 1}}}

In [243]:
get_in(['order', 'items', 0], purchase)

'Apple'

In [244]:
get_in(['order', 'items', 3], purchase,0) # no item found

0

<p>Kidergarden A plans to buy N Christmas presents, and give one for each child. There are five children, whose name a,b,c,d,e. Dut to the convinience, teachers equally split the presents into the number of groups, and bring them to each class. Child c wants present 5, but due to his oldest age, he has to choose the last. What is the Probability child c would be able to choose 5?</p>

In [245]:
num_of_presents=10
target=5
count_of_c_hasachoice=0;c_of_c=count_of_c_hasachoice;
trial=100
P_list=[]
for _ in range(trial):
    for _ in range(trial):
        ll=np.arange(num_of_presents)
        random.shuffle(ll)
        (a,b,*c),(*d,e)=ll[:5],ll[5:]
        if target in c: c_of_c+=1
    P=c_of_c/trial
    P_list.append(P)
    c_of_c=0
np.average(P_list) # App. 30%

0.30409999999999993

#### <p>Amazing Python library Fn.py <a href='https://github.com/kachayev/fn.py'>github</a></p>

In [357]:
from fn import _ as __
list(map(__*2, range(5)))

[0, 2, 4, 6, 8]

In [247]:
list(map(lambda x:x*2, range(5)))

[0, 2, 4, 6, 8]

In [248]:
list(filter(__ < 10, [9,10,11]))

[9]

In [249]:
from fn.op import zipwith
list(zipwith(__+__)([0,1,2], it.repeat(10)))

[10, 11, 12]