In [1]:
from numpy import *

Recarrays and structured arrays

In [9]:
r=ones(3, dtype=dtype([('foo', int), ('bar', float)]))

In [14]:
r['foo']

array([1, 1, 1])

In [11]:
r2 = r.view(recarray)

In [12]:
r2

rec.array([(1, 1.), (1, 1.), (1, 1.)],
          dtype=[('foo', '<i8'), ('bar', '<f8')])

In [15]:
r2.foo

array([1, 1, 1])

In [43]:
for item1,item2 in r2:
    print(item1,',', item2)

1 , 1.0
1 , 1.0
1 , 1.0


In [22]:
data = [ (1, 2), (3, 4.1), (13, 77) ]
dtype = [('x', float), ('y', float)]

In [25]:
print('\n ndarray')
nd = np.array(data);nd


 ndarray


array([[ 1. ,  2. ],
       [ 3. ,  4.1],
       [13. , 77. ]])

In [28]:
print ('\n structured array')
struct_1dtype = np.array(data, dtype=dtype)
print (struct_1dtype['x'])


 structured array
[ 1.  3. 13.]


In [31]:
print('\n structured to ndarray')
struct_1dtype_float = struct_1dtype.view(np.ndarray).reshape(len(struct_1dtype), -1)
print (struct_1dtype_float)


 structured to ndarray
[[( 1.,  2. )]
 [( 3.,  4.1)]
 [(13., 77. )]]


In [42]:
print('\n structured to float: alternative ways - only for case of dtype, but not for structure modification')
struct_1dtype_float_alt = struct_1dtype.view((np.float, len(struct_1dtype.dtype.names)))
# len(struct_1dtype.dtype.names) is  2
print (struct_1dtype_float_alt)


 structured to float: alternative ways
[[ 1.   2. ]
 [ 3.   4.1]
 [13.  77. ]]


In [52]:
# with heterogeneous dtype.
struct_diffdtype = np.array([(1.0, 'string1', 2.0), (3.0, 'string2', 4.1)],
dtype=[('x', float),('str_var', 'a7'),('y',float)])
print('\n structured array with different dtypes')
print (struct_diffdtype,'\n')
struct_diffdtype_nd = struct_diffdtype[['str_var', 'x', 'y']].view(np.ndarray).reshape(len(struct_diffdtype), -1)
print(struct_diffdtype_nd)


 structured array with different dtypes
[(1., b'string1', 2. ) (3., b'string2', 4.1)] 

[[(b'string1', 1., 2. )]
 [(b'string2', 3., 4.1)]]


In [53]:
print('\n structured array with different dtypes to reshaped float array ommiting string columns')
struct_diffdtype_float = struct_diffdtype[['x', 'y']].view(float).reshape(len(struct_diffdtype),-1)
print (struct_diffdtype_float)


 structured array with different dtypes to reshaped float array ommiting string columns
[[1.  2. ]
 [3.  4.1]]


//anaconda/lib/python3.5/site-packages/ipykernel_launcher.py:2: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 

This code may break in numpy 1.16 because this will return a view instead of a copy -- see release notes for details.
  


Slicing

In [55]:
data = array([0.5, 1.2, 2.2, 3.4, 3.5, 3.4, 3.4, 3.4], float)

In [56]:
data[slice(2,4)]

array([2.2, 3.4])

Slicing with bool array 

In [58]:
# create an bool-array for indexing
i = array(len(data)*[False], bool)
i[slice(0,2)]=True
data[i]

array([0.5, 1.2])