In [2]:
import scipy as sci, numpy as np

In [2]:
sci.concatenate(([3],[0]*5,sci.arange(-1,1.002,2/9.0)))

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [3]:
sci.r_[3,[0]*5,-1:1:10j]

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [4]:
sci.r_[3,[0]*5,-1:1:10j,np.array([5,5,5,5])]

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ,  5.        ,  5.        ,  5.        ,  5.        ])

<p style="font-weight:bold;font-size:1.1em;">Making Meshed Array, with rows, columns, and “pages “(in the third dimension)</p>

In [5]:
sci.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [6]:
 sci.mgrid[0:5:4j,0:5:4j]

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.66666667,  1.66666667,  1.66666667,  1.66666667],
        [ 3.33333333,  3.33333333,  3.33333333,  3.33333333],
        [ 5.        ,  5.        ,  5.        ,  5.        ]],

       [[ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ]]])

In [7]:
p = sci.poly1d([3,4,5]);p*p

poly1d([ 9, 24, 46, 40, 25])

In [8]:
p.deriv()

poly1d([6, 4])

In [9]:
p.integ(k=6) #antiderivative (indefinite integral) of this polynomial.
#3x^2->3/3x^3, 4x->4/2x^2, 5->5x, 6<-you have to define

poly1d([ 1.,  2.,  5.,  6.])

<p style="font-weight:bold;font-size:1.1em;">Vectrizing 1-D Array makes everything easy...</p>

In [10]:
def addsubtract(a,b):
    #print(a,b)
    if a > b: return a - b
    else: return a + b

In [11]:
vec_addsubtract=sci.vectorize(addsubtract)
vec_addsubtract([0,3,6,9],[1,3,5,7])

array([1, 6, 1, 2])

<p style="font-weight:500;font-size:1.05em;">Without Vectrizing, you might step this conventional process..</p>

In [12]:
[addsubtract(first,second) for first,second in zip(*([0,3,6,9],[1,3,5,7]))] #((0,1),(3,3),(6,5),(9,7))

[1, 6, 1, 2]

<p style="font-weight:bold;font-size:1.1em;">Applying multiple conditions to miltple (version of) list at once->select() method</p>

In [13]:
x = np.arange(10)
condlist = [x<3, x>5]
choicelist = [x, x**2]
sci.select(condlist, choicelist) 
# Return True item in condiction for each, and at last combine data
# if returned data is overlapped-> the first item's data prioritize

array([ 0,  1,  2,  0,  0,  0, 36, 49, 64, 81])

In [14]:
a=[4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)

array([4, 3, 6])

<p style="font-weight:bold;font-size:1.1em;">Main 3 usage of choose()</p>

In [15]:
choices=np.array([0,1,2,3]*4).reshape(4,4)
choices=choices+np.array([0,10,20,30])[:,sci.newaxis];choices #[:,slice(None)], [:,None]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [16]:
sci.choose([0,1,2,3],choices,mode="clip")

array([ 0, 11, 22, 33])

In [17]:
sci.choose([0,4,4,5],choices,mode="wrap")# if overflow the index, it looks up columns 

array([ 0,  1,  2, 13])

In [18]:
np.array([1,2,3,4])[:,None]

array([[1],
       [2],
       [3],
       [4]])

In [19]:
a=[[1, 0, 1], [0, 1, 0], [1, 0, 1]]
choices_2=[-10, 10]
sci.choose(a,choices_2) # apply 1=10,0=-10

array([[ 10, -10,  10],
       [-10,  10, -10],
       [ 10, -10,  10]])

In [20]:
a=np.array([0, 1]).reshape((2,1,1));a

array([[[0]],

       [[1]]])

In [21]:
c1=np.array([1, 2]).reshape((1,2,1));c1

array([[[1],
        [2]]])

In [22]:
c2=np.array([-1, -2, -3]).reshape((1,1,3));c2

array([[[-1, -2, -3]]])

In [23]:
np.choose(a, (c1, c2))# result is 2x3x5, res[0,:,:]=c1, res[1,:,:]=c2

array([[[ 1,  1,  1],
        [ 2,  2,  2]],

       [[-1, -2, -3],
        [-1, -2, -3]]])

In [24]:
x=np.arange(10)
y=np.ones(10)
sci.who() # returns a list of defined variables and memory consumption–upper bounded

Name               Shape            Bytes            Type

y                  10               80               float64
___                1 x 2 x 1        16               int64
choices            4 x 4            128              int64
c1 (___)           1 x 2 x 1        16               int64
_13                10               80               int64
_19                3 x 3            72               int64
_21 (___)          1 x 2 x 1        16               int64
_6                 2 x 4 x 4        256              float64
_4                 20               160              float64
x                  10               80               int64
_2                 16               128              float64
c2                 1 x 1 x 3        24               int64
_3                 16               128              float64
_14                3                24               int64
_20                2 x 1 x 1        16               int64
_11                4                32        

In [25]:
d={'x': np.arange(2.0), 'y': np.arange(3.0), 'txt':'Some str','idx':5}
np.who(d)

Name            Shape            Bytes            Type

y               3                24               float64
x               2                16               float64

Upper bound on total bytes  =       40


In [4]:
x=np.array([1, 2, 3])
x.repeat(2)

array([1, 1, 2, 2, 3, 3])

In [6]:
np.array([1, 2, 3], float)

array([ 1.,  2.,  3.])

In [9]:
np.array([(1, 2), (3, 4)], dtype=[('x', int), ('y', float)])

array([(1, 2.0), (3, 4.0)], 
      dtype=[('x', '<i8'), ('y', '<f8')])

### <span>Broadcast, NumPy can do operations on arrays whose shapes are mismatched</span>

In [13]:
x=np.array([1, 2])
y=np.array(np.array([3, 4])[:,np.newaxis])
x*y

array([[3, 6],
       [4, 8]])

In [14]:
x=np.arange(5)
mask=(x > 2);mask

array([False, False, False,  True,  True], dtype=bool)

In [16]:
x[mask]=-1;x

array([ 0,  1,  2, -1, -1])

<a href="docs.scipy.org/doc/numpy-1.13.0/glossary.html">Numpy Glossary</a>

### <p>Adcance Indexing</p>

In [19]:
x=np.array([[[1],[2],[3]], [[4],[5],[6]]]);x #2x3x1

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [22]:
#slice (:)
x[1:2,1:2,:] #1-2 for 1d, 1-2 for 2-d, all for 3-d

array([[[5]]])

In [34]:
#Ellipsis
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
x[:,np.newaxis,:,:].shape

(2, 1, 3, 1)

<p style='font-weight:500;font-size:1.1em;color:#2F4F4F'>Warning
The definition of advanced indexing means that x[(1,2,3),] is fundamentally different than x[(1,2,3)]. The latter is equivalent to x[1,2,3] which will trigger basic selection while the former will trigger advanced indexing. Be sure to understand why this occurs.

Also recognize that x[[1,2,3]] will trigger advanced indexing, whereas x[[1,2,slice(None)]] will trigger basic slicing.</p>

In [52]:
y=np.arange(12).reshape(4,3);y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
y[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [54]:
y[(1,2),]

array([[3, 4, 5],
       [6, 7, 8]])

In [55]:
y[[(1,2),slice(None)]]

array([[3, 4, 5],
       [6, 7, 8]])

In [56]:
y[(1,2)]

5

In [57]:
y[[1,2],[1,2]]

array([4, 8])

In [74]:
y=np.arange(9).reshape(3,3);y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### <p>ix_ makes things simpler</p>

In [75]:
gird=np.ix_([0,2],[0,2])

In [76]:
y[gird]

array([[0, 2],
       [6, 8]])

In [77]:
rows=np.array([[0, 0],
               [2, 2]], dtype=np.intp)
columns=np.array([[0, 2],
                  [0, 2]], dtype=np.intp)
y[rows, columns] #[(0,0),(0,2)],[(2,0),(2,2)]

array([[0, 2],
       [6, 8]])

In [84]:
y[np.array([0,2])[:,np.newaxis],np.array([0,2])]

array([[0, 2],
       [6, 8]])

In [85]:
y[np.ix_(np.array([0,2]),np.array([0,2]))] #broadcasting with .ix_

array([[0, 2],
       [6, 8]])

In [86]:
a=[4,3,5,7,6,8]
np.take(a, [[0, 1], [2, 3]])

array([[4, 3],
       [5, 7]])

### <p>Boolean array indexing</p>

In [87]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([ 1.,  2.,  3.])

In [89]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20;x

array([  1.,  19.,  18.,   3.])

In [91]:
x=np.array([[0, 1], 
            [1, 1], 
            [2, 2]])
>>> rowsum = x.sum(-1);rowsum

array([1, 2, 4])

In [92]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [ ]:
rowsum = x.sum(-1, keepdims=True)
>>> rowsum.shape
(3, 1)
>>> #x[rowsum <= 2, :] this is an error

### <p>Boolean array indexing combining with ix_</p>

In [99]:
y=np.arange(12).reshape(4,3);y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [111]:
>>> rows = (y.sum(-1) % 2) == 0 # only sum are even
>>> columns = [0, 2]
>>> y[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

In [114]:
rows=rows.nonzero()[0] #(array([1, 3]),)[0]

In [109]:
y[rows[:, np.newaxis], columns]

array([[ 3,  5],
       [ 9, 11]])

In [118]:
x=np.zeros((2,2), dtype=[('a', np.int32), ('b', np.float64, (3,3))]);x

array([[(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]),
        (0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])],
       [(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]),
        (0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])]], 
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [119]:
x['a'].shape

(2, 2)

In [120]:
x['b'].shape

(2, 2, 3, 3)

In [121]:
x=np.arange(1,7).reshape(2,3);x

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
list(x.flat)

[1, 2, 3, 4, 5, 6]

In [124]:
x.flat[3]

4

In [126]:
x.flat[[1,4]]=1;x

array([[1, 1, 3],
       [4, 1, 6]])

In [136]:
x.flat[[list(range(len(x.flat)))]]

array([[1, 1, 3, 4, 1, 6]])

### <p>Iterate multidimension array(), nditer()</p>

In [143]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [149]:
for x in np.nditer(y): 
    print (x, end =" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [150]:
for x in np.nditer(y.T): 
    print (x, end =" ")

0 1 2 3 4 5 6 7 8 9 10 11 

### <p>Change the iterate order</p>

In [154]:
for x in np.nditer(y.T.copy(order='C')):  #C order or F(Fortran) order  default is K: keep
    print (x, end =" ")

0 3 6 9 1 4 7 10 2 5 8 11 

#### <p>Change the values while nditer: default is read-only. Set the op_flags to modify the values in place.</p><p><u>The index must be ellipsis</u></p>

In [156]:
y2=y.copy()
for x in np.nditer(y2, op_flags=['readwrite']):
    x[...] = 2 * x

In [157]:
y2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [160]:
for x in np.nditer(y2, flags=['external_loop']):
    print(x)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [162]:
for x in np.nditer(y2, flags=['external_loop'],order='F'):
    print(x)

[ 0  6 12 18]
[ 2  8 14 20]
[ 4 10 16 22]


#### <p>Buffering the Array Elements</p>

In [188]:
for x in np.nditer(y2, flags=['external_loop','buffered'],order='F'):
    print(x)

[ 0  6 12 18  2  8 14 20  4 10 16 22]


#### <p>Dealing with Index while iteration</p><p><u>use flags=['f_index']</u></p>

In [166]:
it=np.nditer(y2,flags=['f_index'])
while not it.finished:
    print ("%d <%d>" % (it[0], it.index),end=' ')
    it.iternext()

0 <0> 2 <4> 4 <8> 6 <1> 8 <5> 10 <9> 12 <2> 14 <6> 16 <10> 18 <3> 20 <7> 22 <11> 

In [170]:
it_2=np.nditer(y2, flags=['multi_index'])
while not it_2.finished:
    print ("%d <%s>" % (it_2[0], it_2.multi_index),end=' ')
    it_2.iternext()

0 <(0, 0)> 2 <(0, 1)> 4 <(0, 2)> 6 <(1, 0)> 8 <(1, 1)> 10 <(1, 2)> 12 <(2, 0)> 14 <(2, 1)> 16 <(2, 2)> 18 <(3, 0)> 20 <(3, 1)> 22 <(3, 2)> 

In [183]:
y3=y2.copy()
it_3=np.nditer(y3, flags=['multi_index'], op_flags=['writeonly'])
while not it_3.finished:
    it_3[0] = it_3.multi_index[1] - it_3.multi_index[0]
    it_3.iternext()

In [176]:
y3

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0],
       [-3, -2, -1]])

<p style="color:red;">This is an error: np.nditer(a, flags=['c_index', 'external_loop'])</p>

In [186]:
np.zeros([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

#### <p style="color:red;">nditer, the special broadcasting form: add operands into the list</p><p><u>The flags ‘allocate’ and ‘writeonly’ for operands that are passed in as None.</u> This means we were able to provide just the two operands to the iterator, and it handled the rest.</p>

In [239]:
def square(a):
    it=np.nditer([a, None])
    for x, y in it:
        y[...] = x*x
    return it.operands[1] #this is 'None' values

#it.operands[0] === input === [1,2,3]
square([1,2,3])

(array([1, 2, 3]), array([0, 0, 0]))


array([1, 4, 9])

<p>For completeness, we’ll also add the ‘external_loop’ and ‘buffered’ flags, as these are what you will typically want for performance reasons.</p>

In [237]:
def square_2(a,out=None):
    it=np.nditer([a,out],
                   flags=['external_loop','buffered'],
                   op_flags=[['readonly'], ['writeonly','allocate','no_broadcast']])
    for x,y in it:
        y[...]=x*x
        return it.operands[1]

In [206]:
square_2([1,2,3])

array([1, 4, 9])

In [207]:
b=np.zeros((3,));b

array([ 0.,  0.,  0.])

In [208]:
square_2([1,2,3], out=b)

array([ 1.,  4.,  9.])

In [209]:
b

array([ 1.,  4.,  9.])

In [211]:
# square_2(np.arange(6).reshape(2,3), out=b)
# this is an error, because op_flags has 'no_broadcast'

#### <p style="color:red;">Magic Broadcasting technique without using np.newaxis</p>

In [249]:
#add -1 the axis that is supposed to be one single item dimention of 1 dimension
a=np.arange(3)
b=np.arange(8).reshape(2,4)
it=np.nditer([a,b,None],
             flags=['external_loop'],
             op_axes=[[0,-1,-1], [-1,0,1],None])
#print(it.operands)

(array([0, 1, 2]), array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]]))


In [217]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [214]:
for x,y,z in it: z[...]=x*y

In [215]:
it.operands[2]

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 0,  2,  4,  6],
        [ 8, 10, 12, 14]]])

##### <p style="color:red;">Usual Broadcasting way...</p>

In [220]:
New_=np.newaxis
a[:,New_,New_]*b # 3x1x1 x 1x2x4(or 2x4)

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 0,  2,  4,  6],
        [ 8, 10, 12, 14]]])

#### <p>What's the definition of 'reduction' in scipy?: Aggregating more than one input value is a reduction operation which requires special handling.</p>

<p>!! Any reduction operand be flagged as read-write, and only allows reductions when ‘reduce_ok’ is provided as an iterator flag: Case blow shows how reduce_ok makes it possible to handle a's multidimensional array with op_flags</p>

In [232]:
a = np.arange(24).reshape(2,3,4)
b = np.array(0)
for x, y in np.nditer([a, b], flags=['reduce_ok','external_loop'],
                      op_flags=[['readonly'],['readwrite']]):
    y[...]+=x #relecting the result into the 'b'
    #pass

In [230]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [231]:
b

array(0)

In [250]:
a=np.arange(24).reshape(2,3,4)
it=np.nditer([a, None], flags=['reduce_ok', 'external_loop'],
             op_flags=[['readonly'], ['readwrite', 'allocate']],
             op_axes=[None, [0,1,-1]])
print(it.operands)
it.operands[1][...]=0 #reset the values of array([[ 6, 22, 38], [54, 70, 86]]))
for x, y in it: y[...] += x

(array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]]), array([[ 6, 22, 38],
       [54, 70, 86]]))


In [241]:
it.operands[1]

array([[ 6, 22, 38],
       [54, 70, 86]])

In [242]:
np.sum(a, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [257]:
a = np.arange(24).reshape(2,3,4)
it = np.nditer([a, None], flags=['reduce_ok', 'external_loop',
                                 'buffered', 'delay_bufalloc'],
               op_flags=[['readonly'], ['readwrite', 'allocate']],
               op_axes=[None, [0,1,-1]])
it.operands[1][...]=0
it.reset()
for x,y in it: y[...]+=x

In [258]:
it.operands[1]

array([[ 6, 22, 38],
       [54, 70, 86]])

In [259]:
it.operands

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), array([[ 6, 22, 38],
        [54, 70, 86]]))

Processing individual bands

NameError: name 'im' is not defined

NameError: name 'im_' is not defined